import { get, post, type ApiResponse } from "./real_client";

import type { HITLTask, HITLFilter, HITLTaskDecision, HITLProposedMatch, MatchedEntitySummary, HITLTaskStatus, HITLTaskType, HITLTaskPriority } from "@/types/hitl";

function mapCandidateToTask(cand: any): HITLTask {
  let statusStr = cand.state;
  if (statusStr === "REVIEW_REQUIRED") statusStr = "PENDING";
  else if (statusStr === "APPROVE") statusStr = "APPROVED";
  else if (statusStr === "REJECT") statusStr = "REJECTED";
  else if (statusStr === "DEFER" || statusStr === "ESCALATE") statusStr = "ESCALATED";
  
  return {
    id: cand.candidate_id,
    caseId: cand.case_id,
    caseTitle: "Case " + cand.case_id,
    type: "ENTITY_MERGE" as HITLTaskType,
    priority: "HIGH" as HITLTaskPriority,
    status: statusStr as HITLTaskStatus,
    title: `Candidate Match: ${cand.left?.label || 'Unknown'} <-> ${cand.right?.label || 'Unknown'}`,
    description: `Automated match generated by ${cand.matcher_version || 'system'}.`,
    confidence: cand.confidence || 0,
    flagManualReview: cand.state === "REVIEW_REQUIRED",
    entityAId: cand.left?.entity_id || "",
    entityAName: cand.left?.label || "Unknown",
    entityBId: cand.right?.entity_id || "",
    entityBName: cand.right?.label || "Unknown",
    evidenceIds: cand.evidence_ids || [],
    primaryEvidenceId: cand.evidence_ids?.[0] || "",
    hasContradiction: cand.conflicts && cand.conflicts.length > 0,
    proposedMatch: {
      entityA: { id: cand.left?.entity_id || "", name: cand.left?.label || "", type: cand.left?.kind || "", attributes: cand.left?.attributes || {} },
      entityB: { id: cand.right?.entity_id || "", name: cand.right?.label || "", type: cand.right?.kind || "", attributes: cand.right?.attributes || {} },
      similarityScore: cand.confidence || 0,
      similarityMetrics: [],
      candidateReason: cand.positive_signals ? JSON.stringify(cand.positive_signals) : ""
    },
    createdAt: cand.created_at || new Date().toISOString(),
    updatedAt: cand.created_at || new Date().toISOString(),
    slaDeadline: new Date(Date.now() + 86400000).toISOString()
  };
}

export async function listHITLTasks(filter?: HITLFilter): Promise<ApiResponse<HITLTask[]>> {
  const caseId = filter?.caseId || "";
  if (!caseId) throw new Error("caseId required");
  const data = await get(`/cases/${caseId}/candidates`);
  const tasks = Array.isArray(data) ? data.map(mapCandidateToTask) : [];
  return { data: tasks, meta: { requestId: "req", timestamp: new Date().toISOString(), durationMs: 0, securityClassification: "REAL" } };
}
export async function getHITLTask(taskId: string): Promise<ApiResponse<HITLTask>> {
  const data = await get(`/candidates/${taskId}`);
  return { data: mapCandidateToTask(data), meta: { requestId: "req", timestamp: new Date().toISOString(), durationMs: 0, securityClassification: "REAL" } };
}
export async function submitTaskDecision(taskId: string, decision: HITLTaskDecision): Promise<ApiResponse<HITLTask>> {
  const data = await post(`/candidates/${taskId}/decision`, {
    decision: decision.action === "APPROVE_MERGE" ? "APPROVE" : (decision.action === "REJECT_MERGE" ? "REJECT" : "DEFER"),
    reason: decision.justification
  });
  return { data: mapCandidateToTask(data), meta: { requestId: "req", timestamp: new Date().toISOString(), durationMs: 0, securityClassification: "REAL" } };
}

export async function getHITLStats(caseId?: string): Promise<ApiResponse<any>> {
  if (!caseId) throw new Error("caseId required");
  const data = await get(`/cases/${caseId}/stats`);
  return { data, meta: { requestId: "req", timestamp: new Date().toISOString(), durationMs: 0, securityClassification: "REAL" } };
}

export async function assignTask(taskId: string, analyst: any): Promise<ApiResponse<any>> {
  const data = await post(`/candidates/${taskId}/assign`, { analyst });
  return { data: mapCandidateToTask(data), meta: { requestId: "req", timestamp: new Date().toISOString(), durationMs: 0, securityClassification: "REAL" } };
}
