"""initial schema

Revision ID: 96ad003ca363
Revises: 
Create Date: 2026-09-12 04:39:16.956077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ad003ca363'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_kind', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_trace_id'), 'audit_events', ['trace_id'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('canonical', sa.String(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('access_class', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('kind', 'canonical')
    )
    op.create_index(op.f('ix_entities_canonical'), 'entities', ['canonical'], unique=False)
    op.create_index(op.f('ix_entities_kind'), 'entities', ['kind'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('sensitivity', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('opened_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'user_id')
    )
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('detected_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('scan_engine', sa.String(), nullable=True),
    sa.Column('scan_result', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retention_policy', sa.String(), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('tombstoned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    op.create_table('match_candidates',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('left_entity_id', sa.String(), nullable=False),
    sa.Column('right_entity_id', sa.String(), nullable=False),
    sa.Column('block_key', sa.String(), nullable=False),
    sa.Column('positive_signals', sa.JSON(), nullable=False),
    sa.Column('counter_evidence', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matcher_version', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['left_entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['right_entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_match_candidates_case_id'), 'match_candidates', ['case_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('target_kind', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_case_id'), 'reviews', ['case_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_snapshots_case_id'), 'snapshots', ['case_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('rel_type', sa.String(), nullable=True),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('attribute', sa.String(), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('observed_time', sa.String(), nullable=True),
    sa.Column('valid_from', sa.String(), nullable=True),
    sa.Column('valid_to', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('method_version', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('missingness', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claims_case_id'), 'claims', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_evidence_id'), 'claims', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_claims_source_entity_id'), 'claims', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_claims_target_entity_id'), 'claims', ['target_entity_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_jobs_case_id'), 'jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_jobs_evidence_id'), 'jobs', ['evidence_id'], unique=False)
    op.create_table('provenance',
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('method_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('provenance_id')
    )
    op.create_index(op.f('ix_provenance_claim_id'), 'provenance', ['claim_id'], unique=False)
    op.create_index(op.f('ix_provenance_evidence_id'), 'provenance', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provenance_evidence_id'), table_name='provenance')
    op.drop_index(op.f('ix_provenance_claim_id'), table_name='provenance')
    op.drop_table('provenance')
    op.drop_index(op.f('ix_jobs_evidence_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_case_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_claims_target_entity_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_source_entity_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_evidence_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_case_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_snapshots_case_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_case_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_match_candidates_case_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('case_assignments')
    op.drop_table('cases')
    op.drop_table('users')
    op.drop_index(op.f('ix_entities_kind'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_audit_events_trace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
