"""add classification jurisdiction purpose access_class to evidence

Revision ID: b9b204cf821f
Revises: 96ad003ca363
Create Date: 2026-09-12 18:04:27.912742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b204cf821f'
down_revision: Union[str, Sequence[str], None] = '96ad003ca363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the case-governance snapshot fields (docs/context.md §9.2) to evidence.

    Hand-edited from the autogenerated version: the raw autogenerate emitted these as NOT NULL with no
    default, which fails outright against any database that already has evidence rows (this project's
    own demo/security-check/test databases included) -- Postgres refuses to add a NOT NULL column with
    no way to fill existing rows. Added nullable, backfilled from each row's own case (the same mirror
    this field is supposed to represent, not an arbitrary placeholder), then locked to NOT NULL.
    """
    op.add_column('evidence', sa.Column('classification', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('jurisdiction', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('purpose', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('access_class', sa.String(), nullable=True))
    op.execute(
        """
        UPDATE evidence SET classification = cases.classification, jurisdiction = cases.jurisdiction,
                            purpose = cases.purpose, access_class = cases.sensitivity
        FROM cases WHERE evidence.case_id = cases.case_id
        """
    )
    op.alter_column('evidence', 'classification', nullable=False)
    op.alter_column('evidence', 'jurisdiction', nullable=False)
    op.alter_column('evidence', 'purpose', nullable=False)
    op.alter_column('evidence', 'access_class', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'access_class')
    op.drop_column('evidence', 'purpose')
    op.drop_column('evidence', 'jurisdiction')
    op.drop_column('evidence', 'classification')
    # ### end Alembic commands ###
