"""Court-ready evidence dossier — structured PDF export.

Generates a human-analyst-reviewed dossier following the structure of
BSA 2023 Section 63(4)(c) Part A / Part B certificate fields.

IMPORTANT limitations (displayed in the dossier and must not be removed):
- This is a prototype output from synthetic data.
- It is NOT a legal certificate and does NOT constitute a signed Part A/Part B
  certificate under Section 63 of the Bharatiya Sakshya Adhiniyam, 2023.
- Signature, device, custody, and examiner fields are blank and must be completed
  by an authorised forensic officer before any court submission.
- BSA Section 63(4)(c) compliance requires review by qualified legal counsel.

Design: reportlab PDF, no external API, reproducible, off-line capable.
"""
from __future__ import annotations

import hashlib
import io
from datetime import datetime, timezone
from typing import Optional


# ─── Legal disclaimer (never modify without legal review) ────────────────────
_DISCLAIMER = (
    "PROTOTYPE DOSSIER — SYNTHETIC DATA ONLY\n\n"
    "This document was generated by the DRISHTI-NET prototype from synthetic (fictional) "
    "records. It is not a legal certificate and does not constitute a Part A or Part B "
    "certificate under Section 63 of the Bharatiya Sakshya Adhiniyam, 2023 (BSA 2023). "
    "Signature, device, custody, and examiner fields are intentionally blank and must be "
    "completed by a qualified forensic officer.\n\n"
    "The system proposes candidate relationships for authorized human review; it does not "
    "determine guilt or legal admissibility. No real persons, numbers, accounts, or events "
    "are represented in this synthetic demonstration.\n\n"
    "BSA 2023 Section 63(4)(c) compliance requires review by qualified legal counsel and "
    "a certifying examiner authorised under applicable NCRB / MHA guidelines."
)


def _utc_now_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _sha256_str(s: str) -> str:
    return hashlib.sha256(s.encode()).hexdigest()


def generate_court_pdf(
    case: dict,
    evidence_list: list[dict],
    reviews: list[dict],
    relationships: list[dict],
    analysis: dict,
    merkle_root: Optional[str],
    ledger_anchor: Optional[dict],
    graph_snapshot_id: str,
    analyst_comments: str,
    generated_by: str,
    trace_id: str,
) -> bytes:
    """Generate a court-ready evidence dossier PDF.

    Parameters
    ----------
    case          : case metadata dict (case_id, title, jurisdiction, ...)
    evidence_list : list of evidence dicts with sha256, status, etc.
    reviews       : list of human review decisions
    relationships : aggregated graph edges (already masked)
    analysis      : graph analytics output
    merkle_root   : hex SHA-256 Merkle root, or None if not yet computed
    ledger_anchor : LedgerAnchor dict (tx_hash, block_number, etc.) or None
    graph_snapshot_id : snapshot ID for reproducibility reference
    analyst_comments  : free-text analyst notes
    generated_by  : username of the requesting analyst
    trace_id      : request trace ID for audit trail

    Returns
    -------
    bytes — PDF binary content
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import (HRFlowable, Paragraph, SimpleDocTemplate,
                                        Spacer, Table, TableStyle)
    except ImportError as exc:
        raise RuntimeError(f"reportlab is required for court PDF export: {exc}") from exc

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            rightMargin=20 * mm, leftMargin=20 * mm,
                            topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h2 = styles["Heading2"]
    h3 = styles["Heading3"]
    body = styles["BodyText"]
    mono = ParagraphStyle("mono", parent=body, fontName="Courier", fontSize=8, leading=12)
    warn = ParagraphStyle("warn", parent=body, textColor=colors.darkred, fontSize=9)
    small = ParagraphStyle("small", parent=body, fontSize=8, leading=11)

    def hr():
        return HRFlowable(width="100%", thickness=0.5, color=colors.grey)

    def sp(h=4):
        return Spacer(1, h * mm)

    def tbl(data, col_widths=None):
        t = Table(data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("FONTSIZE", (0, 1), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f8f8")]),
        ]))
        return t

    story = []

    # ── Cover ────────────────────────────────────────────────────────────────
    story.append(Paragraph("DRISHTI-NET Evidence Dossier", h1))
    story.append(Paragraph("Analyst-Reviewed Human Intelligence Summary", h2))
    story.append(hr())
    story.append(sp())
    story.append(Paragraph(f"Case: {case.get('case_id', '')} — {case.get('title', '')}", h2))
    story.append(Paragraph(
        f"Jurisdiction: {case.get('jurisdiction', '')}  |  "
        f"Purpose: {case.get('purpose', '')}  |  "
        f"Classification: {case.get('classification', '')}",
        body))
    story.append(Paragraph(f"Authority reference: {case.get('authority_reference', '')}", body))
    story.append(sp())
    story.append(Paragraph(f"Generated: {_utc_now_str()}", small))
    story.append(Paragraph(f"Generated by: {generated_by}  |  Trace: {trace_id}", small))
    story.append(Paragraph(f"Graph snapshot: {graph_snapshot_id}", small))
    story.append(sp(8))

    # ── Disclaimer (must precede everything else) ─────────────────────────
    story.append(Paragraph("⚠  IMPORTANT NOTICE", h2))
    for line in _DISCLAIMER.split("\n\n"):
        story.append(Paragraph(line.strip(), warn))
        story.append(sp(2))
    story.append(hr())
    story.append(sp())

    # ── BSA 2023 Section 63(4)(c) — Part A fields ────────────────────────
    story.append(Paragraph("PART A — Evidence Certificate Reference Fields", h2))
    story.append(Paragraph(
        "The following fields correspond to the structure of a certificate under BSA 2023 "
        "Section 63(4)(c) and the NCRB Cyber Forensics schedule. These fields must be "
        "completed by a qualified forensic officer before filing.",
        small))
    story.append(sp(3))
    part_a = [
        ["Field", "Value (to be completed by certifying officer)"],
        ["Case Number (FIR / Court Order)", case.get("authority_reference", "[COMPLETE]")],
        ["Name of Certifying Officer / Examiner", "[SIGNATURE REQUIRED]"],
        ["Designation & Organisation", "[COMPLETE]"],
        ["Device / System Examined", "[COMPLETE]"],
        ["Date of Examination", "[COMPLETE]"],
        ["Hash of Electronic Record at Time of Seizure", "[COMPLETE — attach chain-of-custody]"],
        ["Certificate Date", "[COMPLETE]"],
        ["Place", "[COMPLETE]"],
    ]
    story.append(tbl(part_a, col_widths=[80 * mm, 95 * mm]))
    story.append(sp())

    # ── BSA 2023 Section 63(4)(c) — Part B fields ─────────────────────────
    story.append(Paragraph("PART B — Computer / System Attestation Fields", h2))
    story.append(Paragraph(
        "Part B attests that the computer resource used to process and produce this output "
        "was functioning normally and was not subject to unauthorised access.",
        small))
    story.append(sp(3))
    part_b = [
        ["Field", "Value (to be completed by certifying officer)"],
        ["Computer / Server Identifier", "[COMPLETE]"],
        ["Operating System & Version", "[COMPLETE]"],
        ["Authorised User at Time of Processing", generated_by + " (see audit log)"],
        ["Processing Software & Version", "DRISHTI-NET prototype v0.1.0"],
        ["Was the computer functioning normally?", "[YES / NO — certifying officer to attest]"],
        ["Any known hardware/software anomaly?", "[COMPLETE]"],
        ["Signature", "[SIGNATURE REQUIRED]"],
    ]
    story.append(tbl(part_b, col_widths=[80 * mm, 95 * mm]))
    story.append(sp())
    story.append(hr())

    # ── Evidence manifest ────────────────────────────────────────────────
    story.append(Paragraph("Section 1 — Evidence Manifest", h2))
    story.append(Paragraph(
        "Each row is an evidence item accepted and processed under this case. "
        "The SHA-256 hash is an integrity reference computed at upload time; "
        "it is not a chain-of-custody certificate.",
        small))
    story.append(sp(3))
    ev_header = ["Evidence ID", "Filename", "Type", "Status", "SHA-256 (truncated)", "Version"]
    ev_rows = [ev_header] + [
        [
            e.get("evidence_id", ""),
            e.get("filename", ""),
            e.get("record_type", ""),
            e.get("status", ""),
            (e.get("sha256") or "")[:20] + "…",
            str(e.get("version", 1)),
        ]
        for e in evidence_list
    ]
    story.append(tbl(ev_rows, col_widths=[35 * mm, 35 * mm, 22 * mm, 22 * mm, 32 * mm, 14 * mm]))
    story.append(sp())

    # ── Integrity / Merkle root ──────────────────────────────────────────
    story.append(Paragraph("Section 2 — Integrity Reference", h2))
    merkle_display = merkle_root or "(not yet computed — generate via POST /cases/{case_id}/integrity/anchor)"
    story.append(Paragraph(f"Merkle root (SHA-256 of all evidence hashes): {merkle_display}", mono))
    if ledger_anchor:
        status = ledger_anchor.get("anchor_status", "UNKNOWN")
        tx = ledger_anchor.get("tx_hash") or "(none)"
        block = ledger_anchor.get("block_number") or "(none)"
        chain = ledger_anchor.get("chain_id") or "(none)"
        story.append(Paragraph(
            f"Ledger anchor status: {status}  |  Tx: {tx[:16]}…  |  Block: {block}  |  Chain: {chain}",
            mono))
        story.append(Paragraph(
            "NOTE: The ledger anchor stores only the Merkle root — no PII or evidence content. "
            "This is an integrity reference only; it does not constitute legal chain-of-custody proof.",
            small))
    else:
        story.append(Paragraph("No ledger anchor recorded for this dossier.", small))
    story.append(sp())

    # ── Human review decisions ───────────────────────────────────────────
    story.append(Paragraph("Section 3 — Human Review Decisions", h2))
    story.append(Paragraph(
        "Entity resolution candidates were proposed by automated matching rules and decided "
        "by a human reviewer. No automatic identity merge was performed.",
        small))
    story.append(sp(3))
    r_header = ["Candidate", "State", "Left entity", "Right entity", "Confidence", "Reviewer", "Decided"]
    r_rows = [r_header] + [
        [
            (r.get("candidate_id") or r.get("claim_id") or "")[:12],
            r.get("state", ""),
            str(r.get("left") or r.get("entity") or "")[:25],
            str(r.get("right") or r.get("attribute") or "")[:25],
            f"{r['confidence']:.2f}" if "confidence" in r else "",
            r.get("reviewer") or "",
            (r.get("decided_at") or "")[:10],
        ]
        for r in reviews[:50]
    ]
    story.append(tbl(r_rows, col_widths=[22 * mm, 22 * mm, 32 * mm, 32 * mm, 18 * mm, 20 * mm, 20 * mm]))
    story.append(sp())

    # ── Graph relationships ──────────────────────────────────────────────
    story.append(Paragraph("Section 4 — Candidate Relationships (Aggregated, Masked)", h2))
    story.append(Paragraph(
        "Relationships shown are analyst-reviewed candidate connections from the POLE+ graph "
        "projection. Sensitive identifiers are masked by default. These are candidate "
        "relationships for investigator review, not legal findings.",
        small))
    story.append(sp(3))
    rel_header = ["Source", "Relationship", "Target", "Count", "First seen", "Relevance", "Min conf."]
    rel_rows = [rel_header] + [
        [
            str(r.get("source", ""))[:22],
            r.get("rel_type", ""),
            str(r.get("target", ""))[:22],
            str(r.get("count", "")),
            str(r.get("first_seen") or "")[:10],
            str(r.get("relevance", "")),
            f"{float(r['min_confidence']):.2f}" if r.get("min_confidence") is not None else "",
        ]
        for r in relationships[:40]
    ]
    story.append(tbl(rel_rows, col_widths=[30 * mm, 25 * mm, 30 * mm, 12 * mm, 22 * mm, 16 * mm, 15 * mm]))
    story.append(sp())

    # ── Analytics ───────────────────────────────────────────────────────
    story.append(Paragraph("Section 5 — Graph Analytics (Neutral Language)", h2))
    story.append(Paragraph(
        "All analytical labels use neutral language: 'possible bridge', 'high-volume node', "
        "'review priority'. Centrality is a structural observation, not evidence of wrongdoing.",
        small))
    story.append(sp(3))

    bridges = analysis.get("bridge_candidates", [])
    if bridges:
        b_header = ["Label / identifier", "Kind", "Betweenness", "Communities", "Note"]
        b_rows = [b_header] + [
            [b.get("label", "")[:28], b.get("kind", ""), f"{b.get('betweenness', 0):.4f}",
             str(b.get("touches_communities", "")), b.get("note", "")]
            for b in bridges[:15]
        ]
        story.append(tbl(b_rows, col_widths=[40 * mm, 22 * mm, 22 * mm, 22 * mm, 44 * mm]))
        story.append(sp())

    rules = analysis.get("rules", [])
    if rules:
        story.append(Paragraph("Rule-based candidates:", h3))
        for rule in rules[:20]:
            story.append(Paragraph(
                f"• [{rule.get('rule', '')}] {rule.get('explanation', '')} "
                f"(subject: {rule.get('subject', '')})",
                small))
        story.append(sp())

    # ── Analyst comments ─────────────────────────────────────────────────
    story.append(Paragraph("Section 6 — Analyst Comments", h2))
    story.append(Paragraph(analyst_comments or "(none)", body))
    story.append(sp())

    # ── Limitations ──────────────────────────────────────────────────────
    story.append(hr())
    story.append(Paragraph("Limitations", h2))
    limitations = [
        "All data in this prototype is synthetic. No real persons, numbers, or events are represented.",
        "Findings are candidate relationships for authorized human review — not determinations of guilt.",
        "SHA-256 hashes support integrity checking; they do not by themselves prove chain of custody.",
        "The system makes no claim of legal admissibility or BSA 2023 certification.",
        "Entity matches are proposed by rules and decided by a human reviewer; no automatic merge occurs.",
        "The prototype has no live CCTNS/ICJS, telecom, bank, or surveillance connectivity.",
        "Temporal decay affects current relevance only; historical records are not deleted.",
        "OCR extraction accuracy on degraded documents has not been independently benchmarked.",
        "NER model-backed candidates (IndicBERT) require human review before entering the graph.",
    ]
    for lim in limitations:
        story.append(Paragraph(f"• {lim}", small))

    story.append(sp(8))
    story.append(Paragraph(
        "DRISHTI-NET Prototype — Synthetic data only — Not legally certified",
        ParagraphStyle("footer", parent=small, textColor=colors.grey, alignment=1)))

    doc.build(story)
    return buf.getvalue()
