"""Human-reviewed report export (JSON + HTML). Masked by default."""
from __future__ import annotations

import html
import json
from datetime import datetime, timezone

LIMITATIONS = [
    "All records are synthetic. No real persons, numbers, accounts, or events are represented.",
    "Findings are analytical candidates for authorized human review; they are not a determination of guilt, threat, or legal admissibility.",
    "A SHA-256 hash supports integrity checking of stored evidence; it does not by itself prove chain of custody.",
    "The scan gate is fail-closed; in 'testgate' mode it is a documented substitute for a real antivirus engine.",
    "Entity matches are proposed by transparent rules and decided by a human reviewer; no person-level merge is automatic.",
    "Temporal decay affects current relevance only; historical relationships are retained, not rewritten.",
    "Graph analytics (degree, betweenness, communities, rules) are structural observations with neutral labels.",
    "The prototype has no live CCTNS/ICJS, telecom, bank, or surveillance connectivity.",
]

STATEMENT = ("This report was generated by the DRISHTI-NET prototype from synthetic data. Its contents are candidate relationships "
             "and human review decisions. The system does not determine guilt and makes no claim of legal admissibility.")


def build_report(case: dict, evidence: list[dict], reviews: list[dict], relationships: list[dict], analysis: dict,
                 snapshot_id: str, audit_id: str, analyst_comments: str, access_context: dict) -> dict:
    buckets = {k: [] for k in ("APPROVE", "REJECT", "DEFER", "REVERSE", "STALE", "CONTRADICTORY", "REVIEW_REQUIRED")}
    for r in reviews:
        buckets.setdefault(r["state"], []).append(r)
    return {
        "report_version": "0.1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "case": case,
        "scope": {"purpose": case.get("purpose"), "jurisdiction": case.get("jurisdiction"), "classification": case.get("classification")},
        "synthetic_data_notice": "SYNTHETIC_DEMO — all data is fictional.",
        "evidence": evidence,
        "reviewed_candidates": reviews,
        "decisions": {k: len(v) for k, v in buckets.items()},
        "accepted": buckets["APPROVE"], "rejected": buckets["REJECT"], "deferred": buckets["DEFER"],
        "contradictory": buckets["CONTRADICTORY"], "pending": buckets["REVIEW_REQUIRED"],
        "relationships": relationships,
        "analysis": analysis,
        "graph_snapshot_id": snapshot_id,
        "analyst_comments": analyst_comments,
        "limitations": LIMITATIONS,
        "access_context": access_context,
        "audit_id": audit_id,
        "statement": STATEMENT,
    }


def render_html(rep: dict) -> str:
    e = html.escape
    def rows(items, cols):
        if not items:
            return "<p><em>none</em></p>"
        head = "".join(f"<th>{e(c)}</th>" for c in cols)
        body = "".join("<tr>" + "".join(f"<td>{e(str(i.get(c, '')))}</td>" for c in cols) + "</tr>" for i in items)
        return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"
    c = rep["case"]
    parts = [
        "<style>body{font-family:system-ui,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#222}table{border-collapse:collapse;width:100%;font-size:13px;margin:.5rem 0 1rem}th,td{border:1px solid #ccc;padding:4px 6px;text-align:left;vertical-align:top}th{background:#f3f3f3}.notice{background:#fff7d6;border:1px solid #e6c700;padding:.75rem;border-radius:6px}.stmt{border-left:4px solid #888;padding:.5rem 1rem;background:#f7f7f7}</style>",
        f"<h1>DRISHTI-NET Human-Reviewed Report — {e(c['case_id'])}</h1>",
        f"<p class='notice'><strong>{e(rep['synthetic_data_notice'])}</strong></p>",
        f"<p><strong>{e(c['title'])}</strong><br>Jurisdiction: {e(c['jurisdiction'])} · Purpose: {e(c['purpose'])} · Classification: {e(c['classification'])}<br>Generated: {e(rep['generated_at'])} · Graph snapshot: <code>{e(rep['graph_snapshot_id'])}</code> · Audit: <code>{e(rep['audit_id'])}</code></p>",
        "<h2>Access context</h2>", f"<pre>{e(json.dumps(rep['access_context'], indent=1))}</pre>",
        "<h2>Evidence</h2>", rows(rep["evidence"], ["evidence_id", "filename", "record_type", "status", "sha256", "version"]),
        "<h2>Decisions</h2>", rows([{"decision": k, "count": v} for k, v in rep["decisions"].items()], ["decision", "count"]),
        "<h3>Accepted</h3>", rows(rep["accepted"], ["candidate_id", "left", "right", "confidence", "reviewer", "reason", "decided_at"]),
        "<h3>Rejected</h3>", rows(rep["rejected"], ["candidate_id", "left", "right", "confidence", "reviewer", "reason", "decided_at"]),
        "<h3>Deferred</h3>", rows(rep["deferred"], ["candidate_id", "left", "right", "confidence", "reviewer", "reason", "decided_at"]),
        "<h3>Contradictory attributes</h3>", rows(rep["contradictory"], ["entity", "attribute", "value", "evidence_id", "locator"]),
        "<h3>Pending review</h3>", rows(rep["pending"], ["candidate_id", "left", "right", "confidence"]),
        "<h2>Relationships (aggregated, masked)</h2>", rows(rep["relationships"], ["source", "rel_type", "target", "count", "first_seen", "last_seen", "relevance", "evidence_ids", "min_confidence"]),
        "<h2>Analysis (neutral language)</h2>",
        "<h3>Bridge candidates</h3>", rows(rep["analysis"].get("bridge_candidates", []), ["label", "kind", "betweenness", "touches_communities", "note"]),
        "<h3>Rule candidates</h3>", rows(rep["analysis"].get("rules", []), ["rule", "subject", "object", "explanation", "window_start", "window_end"]),
        "<h2>Analyst comments</h2>", f"<p>{e(rep['analyst_comments'] or '(none)')}</p>",
        "<h2>Limitations</h2>", "<ul>" + "".join(f"<li>{e(l)}</li>" for l in rep["limitations"]) + "</ul>",
        f"<p class='stmt'>{e(rep['statement'])}</p>",
    ]
    return "\n".join(parts)
